// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Appliedjob struct {
	Userid        int64  `json:"userid"`
	Jobid         int64  `json:"jobid"`
	Recruiterid   int64  `json:"recruiterid"`
	CurrentStatus string `json:"current_status"`
}

type Education struct {
	ID        sql.NullInt64  `json:"id"`
	School    sql.NullString `json:"school"`
	Course    sql.NullString `json:"course"`
	Startdate sql.NullTime   `json:"startdate"`
	Enddate   sql.NullTime   `json:"enddate"`
}

type Experience struct {
	ID         sql.NullInt64  `json:"id"`
	Title      sql.NullString `json:"title"`
	Company    sql.NullString `json:"company"`
	Startddate sql.NullTime   `json:"startddate"`
	Enddate    sql.NullTime   `json:"enddate"`
	Skills     sql.NullString `json:"skills"`
}

type Job struct {
	ID           int64          `json:"id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Skill        string         `json:"skill"`
	Location     string         `json:"location"`
	Experince    sql.NullString `json:"experince"`
	Compensation sql.NullString `json:"compensation"`
	Postby       int64          `json:"postby"`
}

type Jobseeker struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	Phone     string         `json:"phone"`
	Firstname string         `json:"firstname"`
	Lastname  sql.NullString `json:"lastname"`
	Photo     []byte         `json:"photo"`
	Resume    []byte         `json:"resume"`
	Address   string         `json:"address"`
	City      string         `json:"city"`
	State     string         `json:"state"`
	Pincode   string         `json:"pincode"`
}

type Recommendedjob struct {
	Userid int64 `json:"userid"`
	Jobid  int64 `json:"jobid"`
}

type Recruiter struct {
	ID      int64          `json:"id"`
	Name    sql.NullString `json:"name"`
	Company sql.NullString `json:"company"`
}

type User struct {
	ID         int64  `json:"id"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	Softdelete bool   `json:"softdelete"`
}
